wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.15.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650347426
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 2
      4: 3.9.7
      5: 0.12.14
      6: 4.15.0
      8:
      - 1
      - 5
batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 5.098061509128108e-05
